# 365 Probabilidades — Dia #024
## Qual a probabilidade de você precisar de mais do que 3 a 5 amigos próximos pra se sentir bem?

**Tipo:** Comportamento  
**Data de publicação:** 2026-07-07  
**Ferramenta:** Python  
**Decisão analisada:** Preciso ampliar meu círculo social para ser mais feliz?  
**Hashtag:** #365Probabilidades #Dia024

---

### 📖 A História

Tem um momento na vida em que você para de tentar ter muitos amigos e começa a cuidar dos poucos que importam.

Não sei exatamente quando aconteceu comigo. Mas em algum ponto dos 40, percebi que tinha menos pessoas no meu círculo próximo — e me sentia melhor do que nunca. Mais segura. Mais vista. Menos sozinha, apesar de estar menos "conectada".

Achava que isso era um sinal de algo errado. Que precisaria de mais pessoas, de mais presença, de mais contatos para me sentir bem.

A ciência discorda — com 30 anos de dados para sustentar isso.

---

### 📚 O Conceito: As Camadas de Dunbar

Em 1992, o antropólogo britânico Robin Dunbar descobriu algo que parece simples mas é radical: o tamanho dos grupos sociais dos primatas é proporcional ao tamanho do neocórtex — a região do cérebro responsável pelo processamento social. Ao extrapolar para humanos, ele chegou a uma série de camadas concêntricas de relacionamentos.

A mais íntima, chamada de **"support clique"**, tem em média **5 pessoas**. São aquelas com quem você compartilha crises, vulnerabilidade, e apoio emocional real. A camada seguinte, o **"sympathy group"**, tem em média **15 pessoas** no total — um círculo de amizades próximas, mas com menor intensidade do que as 5 internas.

O bem-estar, segundo as pesquisas, está associado à qualidade dessas duas camadas internas — não ao tamanho das camadas externas (50, 150, 500 pessoas).

Uma meta-análise de 277 estudos conduzida por Wrzus e colegas do Instituto Max Planck mostrou que as redes sociais atingem seu tamanho máximo nos 20 anos — e diminuem gradualmente depois. E que essa diminuição é, em grande parte, **deliberada**: com a maturidade, as pessoas eliminam relacionamentos superficiais e investem mais nas conexões que realmente importam.

---

### 🧮 O Modelo
**Fontes:**
- Dunbar, R.I.M. (1992) — *Neocortex size as a constraint on group size in primates* — Journal of Human Evolution, 22(6), 469-493 (base teórica)
- Dunbar, R.I.M. (1998) — *The social brain hypothesis* — Evolutionary Anthropology, 6(5), 178-190
- Zhou, W.X., Sornette, D., Hill, R.A. & Dunbar, R.I.M. (2005) — *Discrete hierarchical organization of social group sizes* — Proceedings of the Royal Society B, 272, 439-444 (confirmação empírica das camadas 5/15/50/150)
- Wrzus, C., Hänel, M., Wagner, J. & Neyer, F.J. (2013) — *Social network changes and life events across the life span: A meta-analysis* — Psychological Bulletin, 139(1), 53-80 — 277 estudos
- Revisão sistemática BMC Public Health (2022) — *Association between friendship quality and subjective wellbeing among adolescents* — 43 estudos selecionados de 21.585 registros


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

plt.rcParams['font.family'] = 'serif'
plt.rcParams['axes.spines.top'] = False
plt.rcParams['axes.spines.right'] = False
plt.rcParams['axes.grid'] = True
plt.rcParams['grid.alpha'] = 0.3
plt.rcParams['figure.facecolor'] = 'white'
plt.rcParams['axes.facecolor'] = 'white'

print('✅ Bibliotecas carregadas')

✅ Bibliotecas carregadas


In [2]:
# --- DADOS DA LITERATURA ---

# Dunbar (1992, 1998, 2005) — camadas de relacionamentos
# Replicado em múltiplos contextos: offline, Facebook, Twitter, celular
camada_1_intima = 1.5   # parceiro/a ou melhor amigo/a mais próximo
camada_2_suporte = 5    # support clique — apoio emocional real em crises
camada_3_simpatia = 15  # sympathy group — amizades próximas
camada_4_afinidade = 50 # affinity group
camada_5_ativa = 150    # active network (Dunbar number clássico)

# Wrzus et al. (2013) — meta-análise, 277 estudos
# Redes sociais máximas nos 20 anos, diminuição gradual e deliberada depois
n_estudos_wrzus = 277

# Revisão sistemática BMC Public Health (2022) — 43 estudos, adolescentes
# Qualidade > quantidade: evidência consistente
n_estudos_bmc = 43
n_registros_bmc = 21585

# Proporção dos estudos que confirmam qualidade > quantidade
p_qualidade_depressao = 18 / 23   # 18 de 23 estudos: qualidade associada a menos depressao
p_qualidade_solidao = 9 / 10      # 9 de 10 estudos: qualidade associada a menos solidao
p_qualidade_satisfacao = 7 / 7    # 7 de 7 estudos: qualidade associada a mais satisfacao

fator_correcao = 0.80

print('=' * 65)
print('  DADOS DA LITERATURA — AMIZADES E BEM-ESTAR')
print('=' * 65)
print(f'\n  Dunbar (1992/1998/2005) — camadas de relacionamentos:')
print(f'  → Camada 1 (íntima):    ~{camada_1_intima} pessoa')
print(f'  → Camada 2 (suporte):   ~{camada_2_suporte} pessoas')
print(f'  → Camada 3 (simpatia):  ~{camada_3_simpatia} pessoas')
print(f'  → Camada 4 (afinidade): ~{camada_4_afinidade} pessoas')
print(f'  → Camada 5 (ativa):     ~{camada_5_ativa} pessoas')
print(f'\n  Wrzus et al. (2013) — {n_estudos_wrzus} estudos:')
print(f'  → Redes máximas nos 20 anos')
print(f'  → Diminuicao gradual e deliberada com a maturidade')
print(f'\n  Revisao sistematica BMC Public Health (2022):')
print(f'  → {n_estudos_bmc} estudos de {n_registros_bmc:,} registros')
print(f'  → Qualidade → menos depressao: {18} de 23 estudos ({p_qualidade_depressao*100:.0f}%)')
print(f'  → Qualidade → menos solidao:   {9} de 10 estudos ({p_qualidade_solidao*100:.0f}%)')
print(f'  → Qualidade → mais satisfacao:  {7} de 7 estudos ({p_qualidade_satisfacao*100:.0f}%)')
print(f'\n  Fator de correcao: x{fator_correcao}')
print('=' * 65)
print()
print('  ⚠️  NOTA METODOLOGICA:')
print('  Os numeros de Dunbar (5, 15, 50, 150) sao medias — ha grande')
print('  variacao individual. A revisao sistematica do BMC foi feita')
print('  com adolescentes; os efeitos podem ser diferentes em adultos.')
print('  A meta-analise de Wrzus nao separou qualidade de quantidade')
print('  em todos os estudos — e um constructo complexo.')

  DADOS DA LITERATURA — AMIZADES E BEM-ESTAR

  Dunbar (1992/1998/2005) — camadas de relacionamentos:
  → Camada 1 (íntima):    ~1.5 pessoa
  → Camada 2 (suporte):   ~5 pessoas
  → Camada 3 (simpatia):  ~15 pessoas
  → Camada 4 (afinidade): ~50 pessoas
  → Camada 5 (ativa):     ~150 pessoas

  Wrzus et al. (2013) — 277 estudos:
  → Redes máximas nos 20 anos
  → Diminuicao gradual e deliberada com a maturidade

  Revisao sistematica BMC Public Health (2022):
  → 43 estudos de 21,585 registros
  → Qualidade → menos depressao: 18 de 23 estudos (78%)
  → Qualidade → menos solidao:   9 de 10 estudos (90%)
  → Qualidade → mais satisfacao:  7 de 7 estudos (100%)

  Fator de correcao: x0.8

  ⚠️  NOTA METODOLOGICA:
  Os numeros de Dunbar (5, 15, 50, 150) sao medias — ha grande
  variacao individual. A revisao sistematica do BMC foi feita
  com adolescentes; os efeitos podem ser diferentes em adultos.
  A meta-analise de Wrzus nao separou qualidade de quantidade
  em todos os estudos — e um con

In [3]:
# --- O MODELO ---

# Proporcao de estudos confirmando qualidade > quantidade (com IC 95%)
# Usando distribuicao Beta para cada proporcao

# Depressao: 18 de 23
alpha_dep = 18 + 0.5
beta_dep = 5 + 0.5
dist_dep = stats.beta(alpha_dep, beta_dep)
ic_dep = dist_dep.interval(0.95)

# Solidao: 9 de 10
alpha_sol = 9 + 0.5
beta_sol = 1 + 0.5
dist_sol = stats.beta(alpha_sol, beta_sol)
ic_sol = dist_sol.interval(0.95)

# Satisfacao com a vida: 7 de 7
alpha_sat = 7 + 0.5
beta_sat = 0 + 0.5
dist_sat = stats.beta(alpha_sat, beta_sat)
ic_sat = dist_sat.interval(0.95)

print('=' * 65)
print('  MODELO — RESULTADO')
print('=' * 65)
print(f'\n  Proporcao de estudos: qualidade → menos depressao:')
print(f'  → {p_qualidade_depressao*100:.0f}% | IC 95%: [{ic_dep[0]*100:.0f}%, {ic_dep[1]*100:.0f}%]')
print(f'  → Corrigido: {p_qualidade_depressao*fator_correcao*100:.0f}%')
print(f'\n  Proporcao de estudos: qualidade → menos solidao:')
print(f'  → {p_qualidade_solidao*100:.0f}% | IC 95%: [{ic_sol[0]*100:.0f}%, {ic_sol[1]*100:.0f}%]')
print(f'  → Corrigido: {p_qualidade_solidao*fator_correcao*100:.0f}%')
print(f'\n  Proporcao de estudos: qualidade → mais satisfacao com a vida:')
print(f'  → {p_qualidade_satisfacao*100:.0f}% | IC 95%: [{ic_sat[0]*100:.0f}%, {ic_sat[1]*100:.0f}%]')
print(f'  → Corrigido: {p_qualidade_satisfacao*fator_correcao*100:.0f}%')
print(f'\n  CONCLUSAO:')
print(f'  → A camada de suporte real (Dunbar) tem ~5 pessoas')
print(f'  → Qualidade > quantidade em 78-100% dos estudos analisados')
print(f'  → Diminuir o circulo com a maturidade e adaptativo, nao patologico')
print('=' * 65)

  MODELO — RESULTADO

  Proporcao de estudos: qualidade → menos depressao:
  → 78% | IC 95%: [59%, 91%]
  → Corrigido: 63%

  Proporcao de estudos: qualidade → menos solidao:
  → 90% | IC 95%: [62%, 99%]
  → Corrigido: 72%

  Proporcao de estudos: qualidade → mais satisfacao com a vida:
  → 100% | IC 95%: [71%, 100%]
  → Corrigido: 80%

  CONCLUSAO:
  → A camada de suporte real (Dunbar) tem ~5 pessoas
  → Qualidade > quantidade em 78-100% dos estudos analisados
  → Diminuir o circulo com a maturidade e adaptativo, nao patologico


In [4]:
# --- VISUALIZACAO ---

# GRAFICO 1 — As camadas de Dunbar: quem cabe em cada circulo
fig1, ax1 = plt.subplots(figsize=(12, 10))
ax1.set_aspect('equal')

# Circulos concentricos (raio proporcional ao log do tamanho)
camadas = [camada_5_ativa, camada_4_afinidade, camada_3_simpatia, camada_2_suporte, camada_1_intima]
labels_camadas = ['~150 — rede ativa', '~50 — afinidade', '~15 — simpatia', '~5 — suporte', '~1-2 — intimo']
cores_camadas = ['#2a2a28', '#3a3a38', '#4a4a48', '#888884', '#c9a14a']

for i, (tamanho, label, cor) in enumerate(zip(camadas, labels_camadas, cores_camadas)):
    raio = np.log(tamanho + 1) * 1.2
    circulo = plt.Circle((0, 0), raio, color=cor, alpha=0.7, zorder=len(camadas)-i)
    ax1.add_patch(circulo)
    if tamanho >= camada_3_simpatia:
        ax1.text(raio * 0.7, raio * 0.7, label, fontsize=11, color='#f0efe9',
                 ha='left', va='bottom', fontweight='bold')
    else:
        ax1.text(0, raio * 0.4, label, fontsize=11, color='#0d0d0d',
                 ha='center', va='center', fontweight='bold')

ax1.set_xlim(-8, 8)
ax1.set_ylim(-8, 8)
ax1.axis('off')
ax1.set_title('As camadas de Dunbar — quem cabe em cada circulo\nDunbar (1992/1998) · Zhou et al. (2005)',
              fontsize=13, pad=15)

plt.tight_layout()
plt.savefig('dia-024-grafico-01-camadas-dunbar.png', dpi=150, bbox_inches='tight')
plt.close()
print('✅ Grafico 1 salvo!')


# GRAFICO 2 — Qualidade vs quantidade: evidencia dos estudos
fig2, ax2 = plt.subplots(figsize=(12, 8))

dimensoes = ['Menos\ndepressao', 'Menos\nsolidao', 'Mais satisfacao\ncom a vida']
proporcoes = [p_qualidade_depressao * 100, p_qualidade_solidao * 100, p_qualidade_satisfacao * 100]
ic_low = [max(0, (p - ic[0]) * 100) for p, ic in zip(
    [p_qualidade_depressao, p_qualidade_solidao, p_qualidade_satisfacao],
    [ic_dep, ic_sol, ic_sat]
)]
ic_high = [max(0, min((ic[1] - p) * 100, 100 - p * 100)) for p, ic in zip(
    [p_qualidade_depressao, p_qualidade_solidao, p_qualidade_satisfacao],
    [ic_dep, ic_sol, ic_sat]
)]
cores2 = ['#2a8a82', '#c9a14a', '#2a8a82']

bars2 = ax2.bar(dimensoes, proporcoes, color=cores2, alpha=0.85, width=0.45,
                yerr=[ic_low, ic_high], capsize=12,
                error_kw={'elinewidth': 2.5, 'capthick': 2.5})
ax2.set_ylim(0, 115)
ax2.set_ylabel('Proporcao de estudos que confirmam o efeito (%)', fontsize=12)
ax2.set_title('Qualidade de amizade protege — em quase todos os estudos\nRevisao sistematica BMC Public Health (2022) — 43 estudos',
              fontsize=13, pad=15)

for bar, v, il, ih in zip(bars2, proporcoes, ic_low, ic_high):
    ax2.text(bar.get_x() + bar.get_width() / 2, v + ih + 3,
             f'{v:.0f}%', ha='center', fontweight='bold', fontsize=16)

plt.tight_layout()
plt.savefig('dia-024-grafico-02-qualidade-vs-quantidade.png', dpi=150, bbox_inches='tight')
plt.close()
print('✅ Grafico 2 salvo!')


# GRAFICO 3 — Distribuicao Beta: proporcao de estudos (depressao, o mais robusto)
fig3, ax3 = plt.subplots(figsize=(12, 8))

x = np.linspace(0.55, 1.0, 1000)
y = dist_dep.pdf(x)

ax3.plot(x * 100, y, color='#2a8a82', linewidth=3)
ax3.fill_between(x * 100, y, alpha=0.2, color='#2a8a82')
ax3.axvline(x=ic_dep[0] * 100, color='#c9a14a', linestyle='--', linewidth=2,
            label=f'IC 95%: [{ic_dep[0]*100:.0f}%, {ic_dep[1]*100:.0f}%]')
ax3.axvline(x=ic_dep[1] * 100, color='#c9a14a', linestyle='--', linewidth=2)
ax3.axvline(x=p_qualidade_depressao * 100, color='#2a8a82', linewidth=2,
            label=f'Estimativa central: {p_qualidade_depressao*100:.0f}%')

ax3.set_xlabel('Proporcao de estudos: qualidade de amizade associada a menos depressao (%)', fontsize=12)
ax3.set_ylabel('Densidade', fontsize=12)
ax3.set_title('Distribuicao Beta — Qualidade de Amizade e Depressao\nBMC Public Health (2022) — 18 de 23 estudos · prior de Jeffreys',
              fontsize=13, pad=15)
ax3.legend(fontsize=11)

plt.tight_layout()
plt.savefig('dia-024-grafico-03-bayesiano.png', dpi=150, bbox_inches='tight')
plt.close()
print('✅ Grafico 3 salvo!')

✅ Grafico 1 salvo!
✅ Grafico 2 salvo!
✅ Grafico 3 salvo!


### 💡 O Insight

Segundo Robin Dunbar, o cérebro humano tem capacidade cognitiva para manter, em média, apenas **5 pessoas** no círculo de suporte real — aquele onde existe vulnerabilidade genuína, apoio em crises, e presença que importa. A camada seguinte, de **15 pessoas**, inclui amizades próximas, mas com menor intensidade.

E mais: uma meta-análise de **277 estudos** mostrou que as redes sociais atingem seu tamanho máximo nos 20 anos — e diminuem com a maturidade. Não por isolamento. Por escolha. Com a idade, as pessoas eliminam relacionamentos superficiais e investem mais nas conexões que realmente sustentam.

A revisão sistemática de 43 estudos do BMC Public Health confirmou o que Dunbar sugeriu: **qualidade importa mais do que quantidade**. Em 78% dos estudos sobre depressão, 90% dos sobre solidão, e 100% dos sobre satisfação com a vida, amizades de alta qualidade — com intimidade, confiança e presença real — foram associadas a bem-estar significativamente maior.

Você não precisa de mais amigos. Você precisa de melhores conexões com os que já tem.

*Quem está no seu círculo de 5 — as pessoas que você ligaria numa crise às 2 da manhã? E quando foi a última vez que você investiu tempo real nisso?*

---

### ⚠️ Limitações do Modelo
- Os números de Dunbar (5, 15, 50, 150) são médias com grande variação individual — introvertidos tendem a ter círculos menores, extrovertidos maiores, e isso não é patológico em nenhum dos casos
- A revisão sistemática do BMC Public Health foi feita com adolescentes — os efeitos em adultos podem ser diferentes em magnitude, mas a direção (qualidade > quantidade) é consistente com a literatura de adultos também
- A meta-análise de Wrzus et al. (277 estudos) inclui estudos com definições diferentes de "rede social" — o constructo é complexo
- "Qualidade" de amizade foi medida de formas diferentes nos estudos incluídos na revisão (intimidade, confiança, suporte, ausência de conflito) — não é uma medida única e padronizada
- O modelo usa proporção de estudos (não efeito médio) como unidade de análise para o Gráfico 2 — isso reflete a robustez do efeito, não sua magnitude
- O fator de correção (×0,80) foi aplicado às estimativas centrais de proporção

*A ciência é honesta sobre o que não sabe. O modelo também.*

---

### 📎 Links
- Substack: [link do post]
- Instagram: [link do post]

---
*365 Probabilidades · Decidindo com dados, um dia de cada vez.*